name = "MCPRepl"
uuid = "b62cb57a-788d-40b5-9d64-84a1dfc37ce3"
version = "0.3.0"
authors = ["Hans WÃ¼rfel <git@wuerfel.io>", "Kahli Burke <kahli@kahliburke.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OteraEngine = "b2d7f28f-acd6-4007-8b26-bc27716e5513"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
Aqua = "0.8"
Dates = "1.10"
Distributed = "1.11.0"
HTTP = "1.10"
InteractiveUtils = "1.10"
JSON = "1"
JuliaFormatter = "1, 2"
OteraEngine = "1.1.3"
Pkg = "1.10"
Printf = "1.10"
Profile = "1.10"
REPL = "1.10"
Random = "1.10"
SHA = "0.7"
Sockets = "1.11.0"
Suppressor = "0.2.8"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Dates", "Aqua", "JuliaFormatter"]
